### Site info:
title: Matt Gardner's Homepage
author: Matt Gardner
email: mattg@allenai.org
description: "Matt Gardner"
baseurl: /

### Personal info and site tools info:
github_username:  matt-gardner
favicon:     "/images/favicon.ico"
aboutme_photo: https://i.imgur.com/15BT1.jpg # your photo.

### Site setting:
ShowContactInfo: "True"
default_column: "one"

### Build settings
highlighter: rouge
paginate: 5
markdown: redcarpet
kramdown:
  input: GFM  # this was to fix a parsing error, I think with code blocks
